app = "pink-libreddit"
primary_region = "sjc"

[build]
image = "ghcr.io/kotx/redlib"

[env]
REDLIB_DEFAULT_THEME = "laserwave"
REDLIB_ENABLE_RSS = "on"
REDLIB_FULL_URL = "https://r.kot.pink"
REDLIB_ROBOTS_DISABLE_INDEXING = "on"

[http_service]
auto_start_machines = true
auto_stop_machines = "suspend"
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256